name: test

on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest tests/test_bleu.py tests/test_local_recall.py tests/test_meteor.py tests/test_msttr.py tests/test_ngram.py tests/test_rouge.py tests/test_sari.py 